name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------
      # Checkout Code
      # -----------------------------------
      - name: Checkout Code
        uses: actions/checkout@v3

      # -----------------------------------
      # Configure AWS Credentials
      # -----------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # -----------------------------------
      # Login to Amazon ECR
      # -----------------------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # -----------------------------------
      # Build Docker Image
      # -----------------------------------
      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./my-web-app

      # -----------------------------------
      # Tag & Push Image to ECR
      # -----------------------------------
      - name: Tag and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG